/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projparking;

import java.awt.Color;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class CheckOutFrame extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutFrame
     */
    public CheckOutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPlaca = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblTVaga = new javax.swing.JLabel();
        lblVaga = new javax.swing.JLabel();
        lblTModelo = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblTCor = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblTCi = new javax.swing.JLabel();
        lblCi = new javax.swing.JLabel();
        lblTPlaca = new javax.swing.JLabel();
        lblCo = new javax.swing.JLabel();
        btnConclude = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelPlaca1 = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check-out");

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPlaca.setText("Placa :");

        txtPlaca.setText("DWP-4859");
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblTVaga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTVaga.setForeground(new java.awt.Color(102, 102, 102));
        lblTVaga.setText("Vaga :");

        lblVaga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVaga.setForeground(new java.awt.Color(153, 153, 153));

        lblTModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTModelo.setForeground(new java.awt.Color(102, 102, 102));
        lblTModelo.setText("Modelo :");

        lblModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(153, 153, 153));

        lblTCor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTCor.setForeground(new java.awt.Color(102, 102, 102));
        lblTCor.setText("Cor :");

        lblCor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCor.setForeground(new java.awt.Color(153, 153, 153));

        lblTCi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTCi.setForeground(new java.awt.Color(102, 102, 102));
        lblTCi.setText("Data/hr - Entrada :");

        lblCi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCi.setForeground(new java.awt.Color(153, 153, 153));

        lblTPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTPlaca.setForeground(new java.awt.Color(102, 102, 102));
        lblTPlaca.setText("Data/hr - Saída :");

        lblCo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCo.setForeground(new java.awt.Color(153, 153, 153));

        btnConclude.setBackground(new java.awt.Color(255, 255, 255));
        btnConclude.setText("Concluir");
        btnConclude.setEnabled(false);
        btnConclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcludeActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabelPlaca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPlaca1.setText("Valor total :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTCor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPlaca)
                                .addGap(38, 38, 38)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTModelo)
                                    .addComponent(lblTVaga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPlaca1)
                                .addGap(50, 50, 50)
                                .addComponent(lblPreco))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTCi)
                                        .addComponent(lblTPlaca))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnCancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConclude))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTVaga)
                    .addComponent(lblVaga)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTModelo)
                    .addComponent(lblModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCor)
                    .addComponent(lblCor))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCi)
                    .addComponent(lblCi))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTPlaca)
                    .addComponent(lblCo))
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca1)
                    .addComponent(lblPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConclude)
                    .addComponent(btnCancel))
                .addGap(30, 30, 30))
        );

        setBounds(0, 0, 626, 409);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        IndexFrame indexFrame =  new IndexFrame();
        indexFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        FileManager fm = new FileManager();
        try {
            fm.getParkers();
            try {
                Parker p=fm.getParker(txtPlaca.getText());
                if(p!=null){
                    lblCor.setText(p.getCor());
                    lblModelo.setText(p.getModelo());
                    lblVaga.setText(p.getVaga());
                    
                    LocalDateTime dhCi = p.getDataHora();
                    lblCi.setText(dhCi.getHour()+":"+dhCi.getMinute()+"h");
                    
                    LocalDateTime dhCo = LocalDateTime.now();
                    lblCo.setText(dhCo.getHour()+":"+dhCo.getMinute()+"h");
                    
                    
                    
                    int parkingTime = ((dhCo.getHour()*60)+dhCo.getMinute())-((dhCi.getHour()*60)+(dhCi.getMinute()));
                    int completeHours = parkingTime/60;//arredonda para baixo
                    int minutes = parkingTime-(completeHours*60);
                    
                    Taxing t = new Taxing();
                    float parkerTax = 0;
                    float[] possiblePrices = t.load();
                    
                    if(completeHours<1){
                        parkerTax=possiblePrices[0];
                    }
                    else if(completeHours<4){
                        parkerTax=possiblePrices[1];
                    }
                    else if(completeHours<8){
                        parkerTax=possiblePrices[2];
                    }
                    else if(completeHours<24){
                        parkerTax=possiblePrices[3];
                    }
                    else{
                        parkerTax=possiblePrices[3]*(completeHours/24);
                    }
                    
                    System.out.println(completeHours+":"+minutes+"h"); 
                    lblPreco.setForeground(Color.red);
                    lblPreco.setFont(lblPreco.getFont().deriveFont(14));
                    lblPreco.setText("R$ "+parkerTax);
                    
                    btnConclude.setEnabled(true);
                    
                }
                else {
                    JOptionPane.showMessageDialog(this,"Essa placa não corresponde a nenhum carro cadastrado","Campos inválidos",JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
            Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnConcludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcludeActionPerformed
        if(!txtPlaca.getText().equals("")){
            FileManager fm = new FileManager();
            try {
                fm.removeParker(txtPlaca.getText());
                JOptionPane.showMessageDialog(this,"Check-out efetuado com sucesso");
            } catch (IOException ex) {
                Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Ocorreu uma falha, tente novamente.","Falha no sistema",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CheckOutFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Ocorreu uma falha, tente novamente.","Falha no sistema",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                IndexFrame indexF = new IndexFrame();
                indexF.setVisible(true);
                this.setVisible(false);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"A placa do veículo precissa ser informada","Campos inválidos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConcludeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConclude;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCi;
    private javax.swing.JLabel lblCo;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTCi;
    private javax.swing.JLabel lblTCor;
    private javax.swing.JLabel lblTModelo;
    private javax.swing.JLabel lblTPlaca;
    private javax.swing.JLabel lblTVaga;
    private javax.swing.JLabel lblVaga;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
